# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wizq-yahoo 0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "wizq-yahoo"
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Svetlana Tarasova"]
  s.date = "2017-05-29"
  s.email = "ahmadeeva.su@gmail.com"
  s.executables = ["console", "setup"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "README.md",
    "Rakefile"
  ]
  s.homepage = "http://github.com/ahmadeeva-su/wizq-yahoo"
  s.rubygems_version = "2.5.1"
  s.summary = "Wizq Yahoo Mobage integration for Rack & Rails applications"
end
