# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wizq-yahoo 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "wizq-yahoo".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Svetlana Tarasova".freeze]
  s.date = "2020-09-30"
  s.email = "ahmadeeva.su@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install",
    "lib/wizq-yahoo.rb",
    "lib/wizq-yahoo/config.rb",
    "lib/wizq-yahoo/engine.rb",
    "lib/wizq-yahoo/middleware.rb",
    "lib/wizq-yahoo/oauth.rb",
    "lib/wizq-yahoo/payment_validator.rb",
    "lib/wizq-yahoo/rails/controller.rb",
    "lib/wizq-yahoo/rails/controller/redirects.rb",
    "lib/wizq-yahoo/request_validator.rb",
    "lib/wizq-yahoo/user.rb",
    "wizq-yahoo.gemspec"
  ]
  s.homepage = "http://github.com/ahmadeeva-su/wizq-yahoo".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Wizq Yahoo Mobage integration for Rack & Rails application".freeze
end

